[mercuryio]
; To use a custom WACCA IO DLL enter its path here.
; Leave empty if you want to use Segatools built-in keyboard input.
path=waccon_io.dll

[waccon]
; Show mouse cursor
cursor=1
; Enable WinTouch touchscreen input
wintouch=1
; Enable mouse input
mouse=1

; Center position in normalized screen coordinates
; Slightly above the center of the screen works well by default
centerX=0.50
centerY=0.47
; Outer radius
; Relative to the window width, where 1.0 means 100% of the width
radius=1
; Inner radius
; The input area is a ring, in this case from 60% to 100% of the configured radius
innerRadius=0.60
